apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  template:
    spec:
      containers:
        - image: docker.io/ashwini73/todolist-app:2fea85c
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: dev
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  template:
    spec:
      containers:
        - image: docker.io/ashwini73/todolist-app:2fea85c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: dev
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: docker.io/ashwini73/todolist-app:2fea85c
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
        - name: todolist
          image: docker.io/ashwini73/todolist-app:2fea85c
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: development
            - name: mongoDbUrl
              value: mongodb://mongo:27017/todolistDb_dev
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: todolist
  namespace: dev
spec:
  selector:
    app: todolist
  ports:
    - port: 4000
      targetPort: 4000
  type: NodePort
  template:
    spec:
      containers:
        - image: docker.io/ashwini73/todolist-app:2fea85c
---
spec:
  template:
    spec:
      containers:
        - image: docker.io/ashwini73/todolist-app:2fea85c
