apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todolist-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ashwinimhasrup/argocd-TodoList.git
    targetRevision: ""
    path: k8s/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
