apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
        - name: nodetodo
          image: todo:1.0
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: prod
            - name: mongoDbUrl
              value: mongodb://prod-mongo:27017/todolistDb_prod
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: todolist
  namespace: prod
spec:
  selector:
    app: todolist
  ports:
    - port: 4000
      targetPort: 4000
  type: NodePort
