apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
        - name: todolist
          image: todo:1.0
          ports:
            - containerPort: 4000
          env:
            - name: mongoDbUrl
              value: mongodb://mongo:27017/todolistDb
          imagePullPolicy: IfNotPresent
---          
apiVersion: v1
kind: Service
metadata:
  name: todolist
spec:
  selector:
    app: todolist
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP