apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
        - name: nodetodo
          image: docker.io/ashwini73/todolist-app:85a7ce6
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: staging
            - name: mongoDbUrl
              value: mongodb://staging-mongo:27017/todolistDb_staging
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: todolist
  namespace: staging
spec:
  selector:
    app: todolist
  ports:
    - port: 4000
      targetPort: 4000
  type: NodePort
  template:
    spec:
      containers: []
