name: Deploy ArgoCD Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Apply ArgoCD Application
        run: |
          kubectl apply -f - <<EOF
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: argocd-apps
            namespace: argocd
          spec:
            project: default
            source:
              repoURL: https://github.com/ashwinimasrup/argocd-TodoList.git
              targetRevision: feature/test
              path: argocd-apps
            destination:
              server: https://kubernetes.default.svc
              namespace: argocd
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
          EOF
